version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - "3000:80" # Map external port 3000 to internal port 80
    depends_on:
     - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
     - "8080:8080" # Map external port 8080 to internal port 8080