export const Programs = {
  Aerospace: "Aerospace",
  Agricultural_Horticultural_Sciences:
    "Agricultural and Horticultural Sciences",
  Architecture: "Architecture",
  Biochemistry: "Biochemistry",
  Bioeconomy: "Bioeconomy",
  Bioinformatics: "Bioinformatics",
  Brewing_and_Beverage_Technology: "Brewing and Beverage Technology",
  Chemical_Biotechnology: "Chemical Biotechnology",
  Chemical_Engineering: "Chemical Engineering",
  Chemistry: "Chemistry",
  Civil_Engineering: "Civil Engineering",
  Electrical_Engineering_and_Information_Technology:
    "Electrical Engineering and Information Technology",
  Electronics_and_Data_Engineering: "Electronics and Data Engineering",
  Engineering_Science: "Engineering Science",
  Environmental_Engineering: "Environmental Engineering",
  Food_Chemistry: "Food Chemistry",
  Food_Technology: "Food Technology",
  Forest_Science_and_Resource_Management:
    "Forest Science and Resource Management",
  Geodesy_and_Geoinformation: "Geodesy and Geoinformation",
  Geosciences: "Geosciences",
  Health_Science: "Health Science",
  Informatics: "Informatics",
  Games_Engineering: "Informatics: Games Engineering",
  Information_Engineering: "Information Engineering (at TUM Campus Heilbronn)",
  Information_Systems: "Information Systems",
  Landscape_Architecture_and_Landscape_Planning:
    "Landscape Architecture and Landscape Planning",
  Life_Sciences_Biology: "Life Sciences Biology",
  Life_Sciences_Nutrition: "Life Sciences Nutrition",
  Management_and_Data_Science: "Management and Data Science",
  Management_and_Technology_Heilbronn:
    "Management and Technology (am Campus Heilbronn)",
  Management_and_Technology_Munich:
    "Management and Technology (am Campus München)",
  Mathematics: "Mathematics",
  Mechanical_Engineering: "Mechanical Engineering",
  Molecular_Biotechnology: "Molecular Biotechnology",
  Pharmaceutical_Bioprocess_Engineering:
    "Pharmaceutical Bioprocess Engineering",
  Physics: "Physics",
  Political_Science: "Political Science",
  Sport_Science: "Sport Science",
  Sustainable_Management_and_Technology:
    "Sustainable Management and Technology",
  Teaching_Academic_Secondary_Schools_Scientific_Education:
    "Teaching at Academic Secondary Schools – Scientific Education",
  Technology_of_Biogenic_Resources: "Technology of Biogenic Resources",
  Vocational_Education_Agriculture:
    "Vocational Education Agriculture (Teaching at Vocational Schools)",
  Vocational_Education_Electrical_Engineering:
    "Vocational Education Electrical Engineering and Information Technology (Teaching at Vocational Schools)",
  Vocational_Education_Health_and_Health_Care_Science:
    "Vocational Education Health and Health Care Science (Teaching at Vocational Schools)",
  Vocational_Education_Metal_Engineering:
    "Vocational Education Metal Engineering (Teaching at Vocational Schools)",
  Vocational_Education_Nutrition_and_Home_Economics:
    "Vocational Education Nutrition and Home Economics (Teaching at Vocational Schools)",
  Vocational_Education_Structural_Engineering:
    "Vocational Education Structural Engineering (Teaching at Vocational Schools)",
  Aerospace_Engineering: "Aerospace Engineering",
  Agricultural_Biosciences: "Agricultural Biosciences",
  AgriFood_Economics_Policy_and_Regulation:
    "AgriFood Economics, Policy and Regulation",
  Agrosystem_Sciences: "Agrosystem Sciences",
  AI_in_Society: "AI in Society",
  Automotive_Engineering: "Automotive Engineering",
  Biology: "Biology",
  Biomass_Technology: "Biomass Technology",
  Biomedical_Engineering_and_Medical_Physics:
    "Biomedical Engineering and Medical Physics",
  Biomedical_Neuroscience: "Biomedical Neuroscience",
  Business_Education_I: "Business Education I",
  Business_Education_II_with_second_teaching_subject:
    "Business Education II with second teaching subject",
  Cartography: "Cartography",
  Communications_and_Electronics_Engineering:
    "Communications and Electronics Engineering",
  Computational_Mechanics: "Computational Mechanics",
  Computational_Science_and_Engineering_CSE:
    "Computational Science and Engineering (CSE)",
  Conservation_and_Landscape_Planning: "Conservation and Landscape Planning",
  Consumer_Science: "Consumer Science",
  Data_Engineering_and_Analytics: "Data Engineering and Analytics",
  Development_Production_and_Management_in_Mechanical_Engineering:
    "Development, Production and Management in Mechanical Engineering",
  Ecological_Engineering: "Ecological Engineering",
  ESPACE_Earth_Oriented_Space_Science_and_Technology:
    "ESPACE – Earth Oriented Space Science and Technology",
  Executive_MBA_in_Business_and_IT: "Executive MBA in Business & IT",
  Executive_MBA_in_General_Management: "Executive MBA in General Management",
  Executive_MBA_in_Innovation_and_Business_Creation:
    "Executive MBA in Innovation and Business Creation",
  Finance_and_Information_Management_FIM:
    "Finance and Information Management (FIM)",
  Forestry_and_Wood_Science: "Forestry and Wood Science",
  Geomaterials_and_Geochemistry: "Geomaterials and Geochemistry",
  Geophysics: "Geophysics",
  GeoThermie_GeoEnergie: "GeoThermie / GeoEnergie",
  Green_Electronics: "Green Electronics",
  Health_Science_Prevention_and_Health_Promotion:
    "Health Science – Prevention and Health Promotion",
  Human_Factors_Engineering: "Human Factors Engineering",
  Industrial_Biotechnology: "Industrial Biotechnology",
  Industrial_Chemistry: "Industrial Chemistry",
  Information_Technologies_for_the_Built_Environment:
    "Information Technologies for the Built Environment",
  Integrated_Circuit_Design: "Integrated Circuit Design",
  Intellectual_Property_and_Competition_Law_Continuing_Education_Program:
    "Intellectual Property and Competition Law (Continuing Education Program)",
  Land_Management_and_Geospatial_Science:
    "Land Management and Geospatial Science",
  Landscape_Architecture: "Landscape Architecture",
  Lehramt_an_beruflichen_Schulen_Masterstudiengang_Berufliche_Bildung_Integriert:
    "Lehramt an beruflichen Schulen – Masterstudiengang Berufliche Bildung Integriert",
  Logistics_Engineering_and_Management: "Logistics Engineering and Management",
  Management_Heilbronn: "Management (am Campus Heilbronn)",
  Management_Munich: "Management (Main Location: Munich)",
  Management_and_Digital_Technology: "Management and Digital Technology",
  Management_and_Innovation: "Management and Innovation",
  Materials_Science_and_Engineering: "Materials Science and Engineering",
  Mathematical_Finance_and_Actuarial_Science:
    "Mathematical Finance and Actuarial Science",
  Mathematics_in_Data_Science: "Mathematics in Data Science",
  Mathematics_in_Science_and_Engineering:
    "Mathematics in Science and Engineering",
  Matter_to_Life: "Matter to Life",
  Mechatronics_Robotics_and_Biomechanical_Engineering:
    "Mechatronics, Robotics and Biomechanical Engineering",
  Medical_Engineering: "Medical Engineering",
  Neuroengineering: "Neuroengineering",
  Nutrition_and_Biomedicine: "Nutrition and Biomedicine",
  Physics_Applied_and_Engineering_Physics:
    "Physics (Applied and Engineering Physics)",
  Physics_Biophysics: "Physics (Biophysics)",
  Physics_Condensed_Matter_Physics: "Physics (Condensed Matter Physics)",
  Physics_Nuclear_Particle_and_Astrophysics:
    "Physics (Nuclear, Particle and Astrophysics)",
  Politics_and_Technology: "Politics & Technology",
  Power_Engineering: "Power Engineering",
  Quantum_Science_and_Technology: "Quantum Science & Technology",
  Radiation_Biology: "Radiation Biology",
  Rail_and_Urban_Transport: "Rail and Urban Transport",
  Resource_Efficient_and_Sustainable_Building:
    "Resource Efficient and Sustainable Building",
  Responsibility_in_Science_Engineering_and_Technology_RESET:
    "Responsibility in Science, Engineering and Technology (RESET)",
  Risk_and_Safety: "Risk and Safety",
  Robotics_Cognition_Intelligence: "Robotics, Cognition, Intelligence",
  Science_and_Technology_of_Materials_STM:
    "Science and Technology of Materials (STM)",
  Science_and_Technology_Studies_STS: "Science and Technology Studies (STS)",
  Software_Engineering: "Software Engineering",
  Sport_and_Exercise_Science: "Sport and Exercise Science",
  Sustainable_Food: "Sustainable Food",
  Sustainable_Resource_Management: "Sustainable Resource Management",
  Teaching_Academic_Secondary_Schools_Scientific_Education:
    "Teaching at Academic Secondary Schools – Scientific Education",
  Transportation_Systems: "Transportation Systems",
  Urbanism_Urban_and_Landscape_Studies_and_Design:
    "Urbanism – Urban and Landscape Studies and Design",
  Vocational_Education_and_Innovation: "Vocational Education and Innovation",
};

export const Industry = {
  Consulting: "Consulting",
  Finance: "Finance",
  Technology: "Technology",
  Fintech: "Fintech",
  Healthcare: "Healthcare",
  Education: "Education",
  Manufacturing: "Manufacturing",
  Retail: "Retail",
  Real_Estate: "Real Estate",
  Transportation: "Transportation",
  Logistics: "Logistics",
  Energy: "Energy",
  Telecommunications: "Telecommunications",
  Media: "Media",
  Entertainment: "Entertainment",
  Hospitality: "Hospitality",
  Agriculture: "Agriculture",
  Automotive: "Automotive",
  Aerospace: "Aerospace",
  Defense: "Defense",
  Pharmaceuticals: "Pharmaceuticals",
  Biotechnology: "Biotechnology",
  Food_and_Beverage: "Food and Beverage",
  Construction: "Construction",
  Legal: "Legal",
  Public_Sector: "Public Sector",
  Nonprofit: "Nonprofit",
  Sports: "Sports",
  Fashion: "Fashion",
  Music: "Music",
  Arts: "Arts",
  Insurance: "Insurance",
  Mining: "Mining",
  Chemicals: "Chemicals",
  Textiles: "Textiles",
  Forestry: "Forestry",
  Fisheries: "Fisheries",
  Environmental_Services: "Environmental Services",
  Marine: "Marine",
  Printing: "Printing",
  Publishing: "Publishing",
  Advertising: "Advertising",
  Marketing: "Marketing",
  HR_and_Recruitment: "HR and Recruitment",
  Consumer_Goods: "Consumer Goods",
  Electronics: "Electronics",
  Furniture: "Furniture",
  Packaging: "Packaging",
  Professional_Services: "Professional Services",
  Tourism: "Tourism",
  Wellness: "Wellness",
  Personal_Care: "Personal Care",
  Cybersecurity: "Cybersecurity",
  Data_Analytics: "Data Analytics",
  Robotics: "Robotics",
  Artificial_Intelligence: "Artificial Intelligence",
  Space: "Space",
  Gaming: "Gaming",
  E_commerce: "E-commerce",
  Venture_Capital: "Venture Capital",
  Private_Equity: "Private Equity",
  Investment_Banking: "Investment Banking",
  Wealth_Management: "Wealth Management",
  Cryptocurrency: "Cryptocurrency",
  Renewable_Energy: "Renewable Energy",
  Nuclear_Energy: "Nuclear Energy",
  Oil_and_Gas: "Oil and Gas",
  Marine_Engineering: "Marine Engineering",
  Industrial_Engineering: "Industrial Engineering",
  Event_Management: "Event Management",
  Interior_Design: "Interior Design",
  Real_Estate_Development: "Real Estate Development",
  Mortgage_Banking: "Mortgage Banking",
  Property_Management: "Property Management",
  Urban_Planning: "Urban Planning",
  Supply_Chain_Management: "Supply Chain Management",
  Market_Research: "Market Research",
  Business_Intelligence: "Business Intelligence",
  Technical_Writing: "Technical Writing",
  Customer_Service: "Customer Service",
  Quality_Assurance: "Quality Assurance",
  Health_and_Safety: "Health and Safety",
  Medical_Devices: "Medical Devices",
  Clinical_Research: "Clinical Research",
  Social_Media: "Social Media",
  Digital_Marketing: "Digital Marketing",
  Content_Creation: "Content Creation",
  Influencer_Marketing: "Influencer Marketing",
  Animation: "Animation",
  Film: "Film",
  Television: "Television",
  Radio: "Radio",
  Virtual_Reality: "Virtual Reality",
  Augmented_Reality: "Augmented Reality",
  Network_Engineering: "Network Engineering",
  System_Administration: "System Administration",
  Database_Administration: "Database Administration",
  Software_Engineering: "Software Engineering",
  Hardware_Engineering: "Hardware Engineering",
  Technical_Support: "Technical Support",
};

export const BusinessModel = {
  B2C: "B2B",
  C2C: "C2C",
  D2C: "D2C",
  SAAS: "SAAS",
  Subscription: "Subscription",
  Freemium: "Freemium",
  Marketplace: "Marketplace",
  On_Demand: "On-Demand",
  E_Commerce: "E-Commerce",
  Brick_and_Mortar: "Brick and Mortar",
  Franchise: "Franchise",
  Licensing: "Licensing",
  Leasing: "Leasing",
  Freemium_to_Premium: "Freemium to Premium",
  Pay_Per_Use: "Pay Per Use",
};

export const InvestmentStage = {
  Pre_Seed: "Pre-Seed",
  Seed: "Seed",
  Series_A: "Series A",
  Series_B: "Series B",
  Series_C: "Series C",
  Series_D: "Series D",
  Series_E: "Series E",
  Pre_IPO: "Pre-IPO",
  IPO: "IPO",
  Post_IPO: "Post-IPO",
};
